trying to rework the entire ga for wheel building
Signed-off-by: Nick Papior <nickpapior@gmail.com>

diff --git a/.github/workflows/wheels.yaml b/.github/workflows/wheels.yaml
--- a/.github/workflows/wheels.yaml
+++ b/.github/workflows/wheels.yaml
@@ -30,62 +30,142 @@ jobs:
     # and python versions so that builds are ran in parallel.
     # The job matrix is basically copied from https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml
   build_wheels:
-    name: Wheel building
+    name: Wheel building for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
     runs-on: ${{ matrix.os }}
+
     strategy:
-      # If one of the jobs fails, continue with the others.
+      # Ensure that a wheel builder finishes even if another fails
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, macos-13, macos-14]
-        arch: [auto64]
-        toolchain:
-         - {compiler: gcc, version: 11}
-        exclude:
-         - os: macos-14
-           arch: auto64
         include:
-         - os: macos-14
-           arch: arm64
+          # Window 64 bit
+          - os: windows-latest
+            python: 39
+            platform_id: win_amd64
+          - os: windows-latest
+            python: 310
+            platform_id: win_amd64
+          - os: windows-latest
+            python: 311
+            platform_id: win_amd64
+          - os: windows-latest
+            python: 312
+            platform_id: win_amd64
+
+          # Linux 64 bit manylinux2014
+          - os: ubuntu-latest
+            python: 39
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+          - os: ubuntu-latest
+            python: 310
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+          - os: ubuntu-latest
+            python: 311
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+          - os: ubuntu-latest
+            python: 312
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+
+          # MacOS x86_64
+          - os: macos-12
+            python: 39
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 310
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 311
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 312
+            platform_id: macosx_x86_64
+
+          # MacOS arm64
+          - os: macos-14
+            python: 39
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 310
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 311
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 312
+            platform_id: macosx_arm64
+        exclude:
+          - python: 39
+          - python: 311
+          - python: 312
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout sisl
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v5
         with:
-          fetch-depth: 0
-          submodules: false
+          python-version: "3.11"
 
-      # Setup the fortran compiler. This is aware of the operating system.
-      - uses: fortran-lang/setup-fortran@main
-        id: sf
+      - name: Install conda for macos arm64
+        if: ${{ matrix.platform_id == 'macosx_arm64' }}
+        run: |
+          set -ex
+          if [ -d /usr/local/miniconda ]; then
+            # Found a CONDA installation (it might come)
+            echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+            exit 0
+          fi
+
+          # macos arm64 runners do not have conda installed. Thus we much install conda manually
+          EXPECTED_SHA="dd832d8a65a861b5592b2cf1d55f26031f7c1491b30321754443931e7b1e6832"
+          MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
+          curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
+
+          # Check SHA
+          file_sha=$(shasum -a 256 miniforge.sh | awk '{print $1}')
+          if [ "$EXPECTED_SHA" != "$file_sha" ]; then
+            echo "SHA values did not match!"
+            exit 1
+          fi
+
+          # Install miniforge
+          MINIFORGE_PATH=$HOME/miniforge
+          bash ./miniforge.sh -b -p $MINIFORGE_PATH
+          echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
+          echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
+
+      - name: Set conda environment for non-macos arm64 environments
+        if: ${{ matrix.platform_id != 'macosx_arm64' }}
+        run: |
+          # Non-macos arm64 envrionments already have conda installed
+          echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+
+      - name: Build and test wheels
+        env:
+          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
+          CIBW_ARCHS: all
+          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
+          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
+          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash tools/build_tools/repair_windows_wheels.sh {wheel} {dest_dir}
+          CIBW_BEFORE_TEST_WINDOWS: bash tools/build_tools/build_minimal_windows_image.sh ${{ matrix.python }}
+          CIBW_TEST_REQUIRES: pytest
+          CIBW_BEFORE_TEST: bash {project}/tools/build_tools/cibw_before_test.sh
+          CIBW_TEST_COMMAND: bash {project}/tools/build_tools/test_wheels.sh
+          CIBW_TEST_COMMAND_WINDOWS: bash {project}/tools/build_tools/test_windows_wheels.sh ${{ matrix.python }}
+          CIBW_BUILD_VERBOSITY: 1
+
+        run: bash tools/build/wheels/build_wheels.sh
+
+      # Upload the wheel to the action's artifact.
+      - name: Store artifacts
+        uses: actions/upload-artifact@v4
         with:
-          compiler: ${{ matrix.toolchain.compiler }}
-          version: ${{ matrix.toolchain.version }}
-
-      # We use the cibuildwheel action to take care of everything
-      - name: Build wheels (Mac)
-        if: runner.os == 'macOS'
-        uses: pypa/cibuildwheel@v2.19
-        env:
-          CIBW_ARCHS: "${{ matrix.arch }}"
-
-      - name: Build wheels (Linux)
-        if: runner.os == 'Linux'
-        uses: pypa/cibuildwheel@v2.19
-        env:
-          CIBW_ARCHS: "${{ matrix.arch }}"
-          SKBUILD_CMAKE_ARGS: -DCMAKE_Fortran_COMPILER=${{ steps.sf.outputs.fc }};-DCMAKE_C_COMPILER=${{ steps.sf.outputs.cc }}
-
-      - name: Build wheels (Windows)
-        if: runner.os == 'Windows'
-        uses: pypa/cibuildwheel@v2.19
-        env:
-          CIBW_ARCHS: "${{ matrix.arch }}"
-          SKBUILD_CMAKE_ARGS: -DCMAKE_Fortran_COMPILER=${{ steps.sf.outputs.fc }};-DCMAKE_C_COMPILER=${{ steps.sf.outputs.cc }}
-          PIP_NO_CLEAN: "yes"
-
-      # Upload the wheel to the action's articfact.
-      - uses: actions/upload-artifact@v4
-        with:
-          name: artifact-${{ matrix.os }}
+          name: artifact-cp${{ matrix.python }}-${{ matrix.platform_id }}
           path: ./wheelhouse/*.whl
 
   # Build the source distribution as well
@@ -94,12 +174,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: false
 
       - name: Build sdist
-        run: pipx run build --sdist
+        run: |
+          pipx run build --sdist
+          twine check dist/*.tar.gz
 
       - uses: actions/upload-artifact@v4
         with:
